### ISSUE TITLE
uploading images while on local

### ISSUE THREAD

**Issue by saltnpixels** [billerickson/BE-Media-from-Production#11]
Does this make it that uploading images goes to the server and not the local? 
Or it just shows images already in the system as remote?

We are using a remote DB and are trying to find a way that if a dev uploads via the local url it gets added to the production server.

**Comment by billerickson** [comment]
No, this only replaces all of the media URLs on the site to use the remote URL and not local URL. You should go to the remote server to upload new media, then pull down a fresh copy of the database.

**Comment by saltnpixels** [comment]
Thanks for the fast response!

We have been trying to come up with a system where all the devs are using the same DB. 

So you make content changes on the  remote site and then pull down the database each time?

We tried the approach where we are using a remote db set up in wp-config. Then we use the local site to develop, but have to remember to go to the remote site whenever we want to add images.... it can be annoying.
Also we need plugins to be on both production and local. 

One idea we came up with was setting the wp_siteurl to the remote site
```define( 'WP_SITEURL', 'https://psw.local' );```

Then the local site uses the remote site for everything and the back end takes you to the remote back end. Then we made a rewrite rule for just the theme to use the local theme... It works but it would be nicer to be able to access the local admin area for other reasons like testing plugins and stuff...

What is your approach if I may ask?

**Comment by billerickson** [comment]
Since I am typically the only developer working on the site I make content changes locally and push the database to the dev server using WP Migrate DB Pro. 

The only time I have to make changes on the remote server is when uploading media or regenerating thumbnails, in which case I'll:
- Push my current local dev database to the development server
- Upload media and/or regenerate thumbnails
- Pull remote database to local environment

If I had a team of multiple developers, I would follow the same approach we use for production sites - only allow database pulls, not pushes.  Any time you need to make a content change, you must make it on the remote site and pull a fresh copy of the database. You could make local changes to the database but those will need to be manually redone on the remote site.

Database merging is a very difficult problem to solve. Delicious Brains (maker of Migrate DB Pro and other developer plugins) tried solving it with [MergeBot](https://deliciousbrains.com/wp-migrate-db-pro/doc/mergebot/) but it became too difficult and they had to shut it down.

Since databases can't be merged you need to pick a canonical source for content, and that should be the remote / production site.

When using BE Media for Production you won't accidentally forget to upload it to the remote site because if you upload it locally, the image won't load. It will replace the local image URL with the remote site's URL which will 404.

**Comment by saltnpixels** [comment]
thanks for all this info!

I looked into Migrate Pro, but the settings seem to be universally for one local db and one remote db. So two devs cant use it on the same site... I'm not sure how that works. If I set up my local environment and put my settings into the plugin to pull down the db, and another user has his own location and he has to pull down...

then there is the issue of using advanced custom fields with the acf-json folder in the theme. If you edit the fields on the remote site, and then oush your theme, your local acf-json folder will override the remote one. not sure if you use ACF but this is annoying...

**Comment by billerickson** [comment]
You set the remote website to only accept pulls, meaning developers can copy the remote db but cannot override it.

Each developer will pull down the fresh database to their local environment and work. If any database changes are required (content changes, media uploads), the developer make those on the remote site and pull down a fresh copy. That way everyone is working from a single database.

The acf-json directory actually makes this much easier because the metaboxes aren't stored in the database. You can create/edit your ACF metaboxes/options pages/blocks locally, which updates the json file, and include those changes in your git commits which are pushed to GitHub and the remote site. 

Before a developer starts working, they will run `git pull origin master` to get the latest copy of code from GitHub which includes the acf json files. They will get the new metaboxes even without having to pull a fresh copy of the database because the metaboxes are code-based, not stored in the database.
